spring:
  datasource:
    url: jdbc:mysql://localhost/security?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: pass
  thymeleaf:
    cache: false
  sql:
    init:
      mode: always


logging:
  level:
    org.springframework.security: trace
