spring:
  datasource:
    url: jdbc:mysql://localhost/security?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: pass
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.security: trace
